### ISSUE TITLE
Find a plugin support Markdown doc and publish to github

### ISSUE THREAD

**Issue by sunchen115** [ThoughtWorksInc/microbuilder#16]

**Comment by sunchen115** [comment]
Niu yameng and sunchen pick this card

**Comment by Atry** [comment]
可以看一下这个： http://pamflet.databinder.net/Pamflet.html

sun chen notifications@github.com于2015年8月13日周四 下午5:57写道：

**Comment by sunchen115** [comment]
https://github.com/ThoughtWorksInc/rest-rpc/pull/22
