### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/microbuilder#39]
According to this survey, we'll rename it to `Microbuilder`

https://jinshuju.net/f/QosSv3/results

**Comment by Atry** [comment]
We could also move `json-stream` and `sbt-haxe` to `com.thoughtworks.microbuilder` organization.

**Comment by zhanglongyang** [comment]
TODOs:
1. ~~json-stream~~
2. ~~project/sbt-haxe~~
3. ~~project/sbt-rest-rpc~~
4. ~~rest-rpc-core~~
5. ~~rest-rpc-play~~
6. ~~rest-rpc-sample~~
7. ~~rest-rpc~~

**Comment by zhanglongyang** [comment]
Renaming is all done.

**Comment by Atry** [comment]
Great!
