### ISSUE TITLE
Setup sbt-site configuration

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/microbuilder#4]

**Comment by Atry** [comment]
We could setup the web site only for this repository `rest-rpc`, not for the submodules.

**Comment by sunchen115** [comment]
https://github.com/sunchen115/rest-rpc-1/commit/3c2673d1c1f40fa92f55c123bed279ffd9f37ac0

**Comment by sunchen115** [comment]
```
$ cd /path/to/tmpdirectory
$ git clone {your project}
$ cd {your project}
$ git symbolic-ref HEAD refs/heads/gh-pages
$ rm .git/index
$ git clean -fdx
$ echo "My GitHub Page" > index.html
$ git add .
$ git commit -a -m "First pages commit"
$ git push origin gh-pages
$ git checkout master
```

**Comment by Atry** [comment]
Cool

sun chen <notifications@github.com>于2015年8月13日星期四 17:58写道：

> $ cd /path/to/tmpdirectory
> $ git clone {your project}
> $ cd {your project}
> $ git symbolic-ref HEAD refs/heads/gh-pages
> $ rm .git/index
> $ git clean -fdx
> $ echo "My GitHub Page" > index.html
> $ git add .
> $ git commit -a -m "First pages commit"
> $ git push origin gh-pages
> $ git checkout master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThoughtWorksInc/rest-rpc/issues/4#issuecomment-130597740>
> .
>
-- 
杨博 (Yang Bo)

**Comment by sunchen115** [comment]
https://github.com/ThoughtWorksInc/rest-rpc/pull/20

**Comment by sunchen115** [comment]
http://thoughtworksinc.github.io/rest-rpc/latest/api/#package

**Comment by Atry** [comment]
Cool! It seems that everything works! 

Congratulation!
