### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/microbuilder#5]

**Comment by Atry** [comment]
Note that we have to setup Travis CI for each submodules, not only this repository.

**Comment by zhanglongyang** [comment]
https://travis-ci.org/ThoughtWorksInc/rest-rpc-sample/
https://travis-ci.org/ThoughtWorksInc/sbt-rest-rpc
https://travis-ci.org/ThoughtWorksInc/rest-rpc-play
https://travis-ci.org/ThoughtWorksInc/rest-rpc-core
https://travis-ci.org/ThoughtWorksInc/rest-rpc

**Comment by Atry** [comment]
The CI for all other submodules will be broken until we release the first version of each library. It's OK at the moment.
