### ISSUE TITLE
Release to Maven central

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/microbuilder#7]

**Comment by xiaoshao** [comment]
I will do it. pair with bowen

**Comment by Atry** [comment]
But this task will be moved to week 4, after Play caller being implemented.

zwshao notifications@github.com于2015年8月14日周五 下午3:04写道：

**Comment by Atry** [comment]
Request to hosting on maven https://issues.sonatype.org

**Comment by Achoutop** [comment]
See https://issues.sonatype.org/browse/OSSRH-18368

**Comment by Atry** [comment]
See https://issues.sonatype.org/browse/OSSRH-18368

**Comment by Atry** [comment]
Done
